name: Release to Production

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:2.49.4-slim
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Run Code Scan
      run: |
        git config --global safe.directory '*'
        sfdx update
        echo y | sfdx plugins:install sfdx-git-delta
        sf plugins install @salesforce/sfdx-scanner
        mkdir changes
        git fetch --all --quiet
        sfdx sgd:source:delta --to "HEAD" --from origin/master --ignore=.forceignore --output changes  >/dev/null
        sf scanner run --format json --target changes
        
